### ISSUE TITLE
Add tests (travis)

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-wannier90#18]
Add tests with travis, including documentation compilation, and checking that `load_dbenv()` is not needed to do a "bare" `import aiida_wannier90`

**Comment by greschd** [comment]
To clarify (after discussing with Giovanni): It's ok if ``import aiida_wannier90`` fails when the dbenv is not loaded (although we might still choose to make this work). The important part is that the plugin does **not** try to load the dbenv.

**Comment by giovannipizzi** [comment]
@greschd can you try to add a simple travis test, if you happen to have time?
BTW, for now we cannot use the plugin fixtures because they are not in 0.10.0 but only in develop, and we cannot make this plugin depend on it...

**Comment by greschd** [comment]
I'll look into it. Not quite sure if ``aiida-pytest`` works nicely with Travis right now, but it should be doable.

**Comment by greschd** [comment]
@giovannipizzi Could you enable Travis for aiida-wannier90? It seems I don't have the rights to do that.

**Comment by giovannipizzi** [comment]
Just did, with the option "build only if .travis.yml is present"

**Comment by greschd** [comment]
Perfect, thanks.

**Comment by greschd** [comment]
Added a Travis run, which clones and compiles Wannier90 and then runs the local tests. Since it needs the ``AIIDA_PATH`` feature, ``aiida-core`` is currently installed from GitHub as well, but that can be changed after the 0.10 release. 

Also had to fix the tests and the parser, due to the change from ``KpointsData`` to ``ParameterData`` in the ``kpoint_path`` variable.

Finally, added ``YAPF`` formatting, which accounts for most of the changes in the code.
