### ISSUE TITLE
Update test_local_input.py to use the current testing framework

### ISSUE THREAD

**Issue by DanielMarchand** [aiidateam/aiida-wannier90#28]
test_local_input, test_changed_seedname, test_changed_seedname_empty_settings,etc. Are based on the old pytest methods. The need to be updated to work with the new AiiDAplugintests

**Comment by greschd** [comment]
Would you mind expanding on this a comment a bit? Since I haven't been at the plugin migration workshop, I'm not familiar with what the current best practices for testing are. Do you know if this is documented somewhere, or if there is an example in another plugin?

From looking at the AiiDA fixtures source, I think (might be wrong) that they support creating a DB / profile, but setting up of computers and codes is not implemented yet. So, I updated ``aiida_pytest`` to use the built-in fixtures for that, and set up computers, codes, and start the daemon as before.

**Comment by greschd** [comment]
Related discussion see #25

**Comment by DanielMarchand** [comment]
Just a brief comment on your question here. For me pytest is fine. The reason why I wrote we needed to move to AiiDAplugintests was because I was under the impresssion that aiida_pytest would no longer be maintained and would never again work with the new AiiDA. So long as this is not the case we can continue to use pytest. I'll send you the materials I have regarding the new testing conventions (I think they might not even be so different from aiida_pytest, but since I am not at all familiar with aiida_pytest I cannot really comment directly). You can take a look and we can discuss later whether to keep aiida_pytest or not.

**Comment by giovannipizzi** [comment]
Can this be closed for now?

**Comment by greschd** [comment]
Yeah, I think we'll wait for https://github.com/aiidateam/aiida-core/issues/3473 before looking to get rid of ``aiida-pytest`` completely.
