### ISSUE TITLE
Reactivate precommit prospector

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-wannier90#46]
Some errors come from the pytests because of apparently unused imports, due to the way pytest works.

I suggest to first fix the problematic tests in #45 and then work on this issue.

**Comment by normarivano** [comment]
@greschd, I'm currently working on cleaning the code in order to fix the reasons for which the prospector fails before reactivate it. One of the messages concerns this:
https://github.com/aiidateam/aiida-wannier90/blob/de8fc8531622d6d2024368fb28e626352e2bb4d2/aiida_wannier90/io/_group_list.py#L23-L25
I get the following:
`pylint: useless-else-on-loop / Else clause on loop without a break statement (col 4)`

Any idea/suggestion to fix it? Thanks a lot.

**Comment by greschd** [comment]
Yeah, that code is equivalent to
```python
    # final group
    groups.append(sorted(set([current_start, v2])))
    return groups
```
because there's no ``break`` statement in the for-loop, so the ``else`` statement is always executed.

**Comment by normarivano** [comment]
Ok, perfect! Thank you.
